-- =========================================================
-- STORE MANAGEMENT - CONVENIENCE STORE
-- SQL Server / SSMS
-- Admin + Employee: dùng chung bảng Users, phân quyền bằng role.
-- Customer: tài khoản riêng cho App.
-- Schema bám theo ERD: Users, Customers, Categories, Products,
-- Suppliers, Purchase Orders, Promotions (3 loại), Orders, Payments...
-- =========================================================
-- IMPORTANT:
-- 1) If you already have data in the original DB, adding constraints may fail. 
--    Use data-cleaning steps first (ensure referential integrity), or import into a fresh DB.
-- 2) To add constraints to an existing DB with data, you can:
--    a) In SQL Server, do NOT use MySQL's SET FOREIGN_KEY_CHECKS.
--       Instead, clean orphan/duplicate data before adding constraints.
--    b) Or create the database fresh so all referenced keys exist.
-- 3) Backup your current DB before running this script.
-- File generated by ChatGPT for your project.
-- IMPORTANT: switch to master BEFORE dropping store_management.
-- Otherwise SSMS may be connected to store_management and SQL Server
-- will return: Cannot drop database because it is currently in use.
USE master;
GO

IF DB_ID(N'store_management') IS NOT NULL
BEGIN
    ALTER DATABASE [store_management] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [store_management];
END;
GO

CREATE DATABASE [store_management];
GO

USE [store_management];
GO

IF OBJECT_ID(N'ai_messages', N'U') IS NOT NULL DROP TABLE ai_messages;
IF OBJECT_ID(N'ai_conversations', N'U') IS NOT NULL DROP TABLE ai_conversations;

IF OBJECT_ID(N'activity_logs', N'U') IS NOT NULL DROP TABLE activity_logs;
IF OBJECT_ID(N'promotion_redemptions', N'U') IS NOT NULL DROP TABLE promotion_redemptions;
IF OBJECT_ID(N'voucher_promotions', N'U') IS NOT NULL DROP TABLE voucher_promotions;
IF OBJECT_ID(N'event_promotions', N'U') IS NOT NULL DROP TABLE event_promotions;
IF OBJECT_ID(N'product_promotions', N'U') IS NOT NULL DROP TABLE product_promotions;
IF OBJECT_ID(N'payments', N'U') IS NOT NULL DROP TABLE payments;
IF OBJECT_ID(N'order_items', N'U') IS NOT NULL DROP TABLE order_items;
IF OBJECT_ID(N'[orders]', N'U') IS NOT NULL DROP TABLE [orders];
IF OBJECT_ID(N'po_details', N'U') IS NOT NULL DROP TABLE po_details;
IF OBJECT_ID(N'purchase_orders', N'U') IS NOT NULL DROP TABLE purchase_orders;
IF OBJECT_ID(N'inventory_adjustments', N'U') IS NOT NULL DROP TABLE inventory_adjustments;
IF OBJECT_ID(N'inventory', N'U') IS NOT NULL DROP TABLE inventory;
IF OBJECT_ID(N'products', N'U') IS NOT NULL DROP TABLE products;
IF OBJECT_ID(N'units', N'U') IS NOT NULL DROP TABLE units;
IF OBJECT_ID(N'suppliers', N'U') IS NOT NULL DROP TABLE suppliers;
IF OBJECT_ID(N'categories', N'U') IS NOT NULL DROP TABLE categories;
IF OBJECT_ID(N'customers', N'U') IS NOT NULL DROP TABLE customers;
IF OBJECT_ID(N'users', N'U') IS NOT NULL DROP TABLE users;
IF OBJECT_ID(N'promotions', N'U') IS NOT NULL DROP TABLE promotions;

-- Parent tables first
CREATE TABLE categories (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(191) NOT NULL,
  slug VARCHAR(191) DEFAULT NULL,
  description NVARCHAR(MAX),
  is_active BIT NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  -- SQL Server: dùng filtered unique index bên dưới để cho phép nhiều NULL
);

CREATE TABLE suppliers (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  contact_name VARCHAR(255),
  phone VARCHAR(50),
  email VARCHAR(255),
  address NVARCHAR(MAX),
  is_active BIT NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
  id INT IDENTITY(1,1) PRIMARY KEY,
  full_name NVARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  password_hash VARCHAR(512) DEFAULT NULL,
  email VARCHAR(255),
  reward_points INT NOT NULL DEFAULT 0,
  address NVARCHAR(MAX),
  note NVARCHAR(MAX),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  is_active BIT NOT NULL DEFAULT 1,
  -- Khách hàng đăng nhập App; tài khoản nhân viên/admin nằm ở Users.
  -- SQL Server: dùng filtered unique indexes bên dưới để cho phép nhiều NULL.
);
GO
CREATE UNIQUE INDEX ux_customers_phone
ON customers(phone)
WHERE phone IS NOT NULL;

CREATE UNIQUE INDEX ux_customers_email
ON customers(email)
WHERE email IS NOT NULL;
GO


CREATE TABLE users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  username VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(512) NOT NULL,
  first_name NVARCHAR(100) NOT NULL,
  last_name NVARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(20),
  role VARCHAR(20) NOT NULL DEFAULT 'employee',
  is_active BIT NOT NULL DEFAULT 1,
  locked BIT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_login DATETIME DEFAULT NULL,
  CONSTRAINT ck_users_role CHECK (role IN ('admin','employee'))
);
GO
CREATE UNIQUE INDEX ux_users_email
ON users(email)
WHERE email IS NOT NULL;
GO

CREATE TABLE promotions (
  id INT IDENTITY(1,1) PRIMARY KEY,
  code VARCHAR(100) NOT NULL UNIQUE,
  name NVARCHAR(150) NOT NULL,
  type VARCHAR(20) NOT NULL,
  description NVARCHAR(1000),
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  max_discount DECIMAL(12,2) DEFAULT NULL,
  usage_limit INT DEFAULT NULL,
  used_count INT NOT NULL DEFAULT 0,
  is_deleted BIT NOT NULL DEFAULT 0,
  deleted_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_promotions_type CHECK (type IN ('product','event','voucher')),
  CONSTRAINT ck_promotions_status CHECK (status IN ('active','expired','disabled')),
  CONSTRAINT ck_promotions_dates CHECK (end_date >= start_date),
  CONSTRAINT ck_promotions_usage CHECK (usage_limit IS NULL OR usage_limit >= 0),
  CONSTRAINT ck_promotions_used_count CHECK (used_count >= 0)
);

-- =========================================================
-- PROMOTION DETAILS: 3 loại khuyến mãi theo ERD
-- =========================================================

-- Event/voucher details
CREATE TABLE event_promotions (
  id INT IDENTITY(1,1) PRIMARY KEY,
  promotion_id INT NOT NULL UNIQUE,
  min_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_percent DECIMAL(5,2) NOT NULL,
  max_discount_amount DECIMAL(12,2) DEFAULT NULL,
  CONSTRAINT fk_event_promotions_promotion
    FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
  CONSTRAINT ck_event_min_order CHECK (min_order_amount >= 0),
  CONSTRAINT ck_event_discount CHECK (discount_percent >= 0 AND discount_percent <= 100)
);

CREATE TABLE voucher_promotions (
  id INT IDENTITY(1,1) PRIMARY KEY,
  promotion_id INT NOT NULL UNIQUE,
  voucher_code VARCHAR(50) NOT NULL UNIQUE,
  discount_percent DECIMAL(5,2) NOT NULL,
  max_discount_amount DECIMAL(12,2) DEFAULT NULL,
  usage_limit INT DEFAULT NULL,
  used_count INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_voucher_promotions_promotion
    FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
  CONSTRAINT ck_voucher_discount CHECK (discount_percent >= 0 AND discount_percent <= 100),
  CONSTRAINT ck_voucher_usage CHECK (usage_limit IS NULL OR usage_limit >= 0),
  CONSTRAINT ck_voucher_used_count CHECK (used_count >= 0)
);

CREATE TABLE units (
  id INT IDENTITY(1,1) PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  is_active BIT NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_units_code ON units (code);

-- Products with FK to categories and suppliers
CREATE TABLE products (
  id INT IDENTITY(1,1) PRIMARY KEY,
  sku VARCHAR(100) DEFAULT NULL,
  product_name VARCHAR(255) NOT NULL,
  barcode VARCHAR(191) DEFAULT NULL,
  category_id INT DEFAULT NULL,
  supplier_id INT DEFAULT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost DECIMAL(12,2) DEFAULT 0,
  unit_id INT DEFAULT NULL,
  description NVARCHAR(MAX),
  image_url VARCHAR(1024) DEFAULT NULL,
  is_active BIT NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_products_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE SET NULL ON UPDATE CASCADE
);
GO

-- SQL Server: filtered unique indexes allow NULL SKU/barcode values.
CREATE UNIQUE INDEX ux_products_sku
ON products(sku)
WHERE sku IS NOT NULL;

CREATE UNIQUE INDEX ux_products_barcode
ON products(barcode)
WHERE barcode IS NOT NULL;
GO

CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_supplier ON products (supplier_id);
CREATE INDEX idx_products_unit ON products (unit_id);

-- Promotion áp dụng theo từng sản phẩm
CREATE TABLE product_promotions (
  id INT IDENTITY(1,1) PRIMARY KEY,
  promotion_id INT NOT NULL,
  product_id INT NOT NULL,
  discount_percent DECIMAL(5,2) NOT NULL,
  CONSTRAINT fk_product_promotions_promotion
    FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_promotions_product
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT ck_product_promotions_discount CHECK (discount_percent >= 0 AND discount_percent <= 100),
  CONSTRAINT ux_product_promotions UNIQUE (promotion_id, product_id)
);


-- Inventory: one record per product (normalized). Use product_id unique.
CREATE TABLE inventory (
  id INT IDENTITY(1,1) PRIMARY KEY,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  last_checked_at DATETIME DEFAULT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ux_inventory_product UNIQUE (product_id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_inventory_product ON inventory (product_id);

-- Inventory adjustments log
CREATE TABLE inventory_adjustments (
  id INT IDENTITY(1,1) PRIMARY KEY,
  product_id INT NOT NULL,
  change_amount INT NOT NULL,
  reason VARCHAR(255) DEFAULT NULL,
  user_id INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_adj_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_inv_adj_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_inv_adj_product ON inventory_adjustments (product_id);
CREATE INDEX idx_inv_adj_user ON inventory_adjustments (user_id);


-- =========================================================
-- PURCHASE ORDERS: nhập hàng từ nhà cung cấp
-- =========================================================
CREATE TABLE purchase_orders (
  id INT IDENTITY(1,1) PRIMARY KEY,
  po_code VARCHAR(20) NOT NULL UNIQUE,
  supplier_id INT NOT NULL,
  user_id INT NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  note NVARCHAR(MAX),
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_orders_supplier
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT fk_purchase_orders_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT ck_purchase_orders_status CHECK (status IN ('pending','completed','cancelled'))
);

CREATE TABLE po_details (
  id INT IDENTITY(1,1) PRIMARY KEY,
  purchase_order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  import_price DECIMAL(12,2) NOT NULL,
  subtotal AS (quantity * import_price) PERSISTED,
  CONSTRAINT fk_po_details_po
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_po_details_product
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE NO ACTION,
  CONSTRAINT ck_po_details_quantity CHECK (quantity > 0),
  CONSTRAINT ck_po_details_import_price CHECK (import_price >= 0),
  CONSTRAINT ux_po_details_product UNIQUE (purchase_order_id, product_id)
);

CREATE INDEX idx_purchase_orders_supplier ON purchase_orders(supplier_id);
CREATE INDEX idx_purchase_orders_user ON purchase_orders(user_id);
CREATE INDEX idx_po_details_product ON po_details(product_id);

-- Orders and order items
CREATE TABLE [orders] (
  id INT IDENTITY(1,1) PRIMARY KEY,
  order_number VARCHAR(100) NOT NULL UNIQUE,
  customer_id INT DEFAULT NULL,
  employee_id INT DEFAULT NULL,
  promotion_id INT DEFAULT NULL,
  order_type VARCHAR(20) NOT NULL DEFAULT 'pos',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(20) DEFAULT NULL,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  note NVARCHAR(MAX),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_orders_employee FOREIGN KEY (employee_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_orders_promo FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT ck_orders_type CHECK (order_type IN ('pos','mobile')),
  CONSTRAINT ck_orders_status CHECK (status IN ('pending','processing','completed','cancelled')),
  CONSTRAINT ck_orders_payment_method CHECK (payment_method IS NULL OR payment_method IN ('cash','card','e_wallet')),
  CONSTRAINT ck_orders_payment_status CHECK (payment_status IN ('pending','paid','failed')),
  CONSTRAINT ck_orders_amounts CHECK (subtotal >= 0 AND discount >= 0 AND total_amount >= 0)
);
CREATE INDEX idx_orders_customer ON [orders] (customer_id);
CREATE INDEX idx_orders_employee ON [orders] (employee_id);
CREATE INDEX idx_orders_status ON [orders] (status);
CREATE INDEX idx_orders_type ON [orders] (order_type);
CREATE INDEX idx_orders_payment_status ON [orders] (payment_status);



CREATE TABLE order_items (
  id INT IDENTITY(1,1) PRIMARY KEY,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES [orders](id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE NO ACTION ON UPDATE CASCADE
);
CREATE INDEX idx_oi_order ON order_items (order_id);
CREATE INDEX idx_oi_product ON order_items (product_id);


-- Payments linked to orders
CREATE TABLE payments (
  id INT IDENTITY(1,1) PRIMARY KEY,
  order_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  method VARCHAR(20) NOT NULL DEFAULT 'cash',
  transaction_ref VARCHAR(255) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'completed',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES [orders](id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_payments_order ON payments (order_id);


-- Optional: Promotion redemptions to track usage per customer/order
CREATE TABLE promotion_redemptions (
  id INT IDENTITY(1,1) PRIMARY KEY,
  promotion_id INT NOT NULL,
  customer_id INT DEFAULT NULL,
  order_id INT DEFAULT NULL,
  redeemed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pr_promotion FOREIGN KEY (promotion_id) REFERENCES promotions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pr_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pr_order FOREIGN KEY (order_id) REFERENCES [orders](id) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX idx_pr_promotion ON promotion_redemptions (promotion_id);
CREATE INDEX idx_pr_customer ON promotion_redemptions (customer_id);

-- Activity / Audit logs
CREATE TABLE activity_logs (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  user_id INT DEFAULT NULL,
  action VARCHAR(191) NOT NULL, -- e.g., "create_order", "adjust_inventory"
  entity_type VARCHAR(100) DEFAULT NULL, -- e.g., "orders", "products"
  entity_id VARCHAR(100) DEFAULT NULL,
  payload NVARCHAR(MAX) DEFAULT NULL,
  ip_address VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_activity_user ON activity_logs (user_id);
CREATE INDEX idx_activity_action ON activity_logs (action);

-- Helpful indexes for reporting queries
CREATE INDEX idx_orders_created_at ON [orders] (created_at);
CREATE INDEX idx_inventory_quantity ON inventory (quantity);
CREATE INDEX idx_products_created_at ON products (created_at);

-- ===== USERS (ADMIN + EMPLOYEE, phân quyền bằng role) =====
INSERT INTO users
(username, password_hash, first_name, last_name, email, phone, role, is_active, locked, created_at)
VALUES
  ('admin', '$2a$11$B5Pre4vLwlsfDIMg/gXXjuH/CyqianiPXHXSXikWE5R0djN/9Tf7.', N'Quản trị', N'Viên', 'admin@example.com', '0909000000', 'admin', 1, 0, GETDATE()),
  ('staff01', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', N'Nguyễn Văn', N'A', 'staff01@example.com', '0909000001', 'employee', 1, 0, GETDATE()),
  ('staff02', '$2a$11$NChyYqe5MniZi.l08LVuP.SkfLMRMtyK6guvRRyq/PdaGdjYoTaO2', N'Lê Thị', N'B', 'staff02@example.com', '0909000002', 'employee', 1, 0, GETDATE());

-- password của admin là admin123
-- password của employee là 123456


-- ===== CUSTOMERS (full_name, phone, email, address) =====
INSERT INTO customers (full_name, phone, email, address, created_at)
VALUES
('Khách hàng 1', '0909000001', 'kh1@mail.com', 'Địa chỉ 1', GETDATE()),
('Khách hàng 2', '0909000002', 'kh2@mail.com', 'Địa chỉ 2', GETDATE()),
('Khách hàng 3', '0909000003', 'kh3@mail.com', 'Địa chỉ 3', GETDATE()),
('Khách hàng 4', '0909000004', 'kh4@mail.com', 'Địa chỉ 4', GETDATE()),
('Khách hàng 5', '0909000005', 'kh5@mail.com', 'Địa chỉ 5', GETDATE()),
('Khách hàng 6', '0909000006', 'kh6@mail.com', 'Địa chỉ 6', GETDATE()),
('Khách hàng 7', '0909000007', 'kh7@mail.com', 'Địa chỉ 7', GETDATE()),
('Khách hàng 8', '0909000008', 'kh8@mail.com', 'Địa chỉ 8', GETDATE()),
('Khách hàng 9', '0909000009', 'kh9@mail.com', 'Địa chỉ 9', GETDATE()),
('Khách hàng 10', '0909000010', 'kh10@mail.com', 'Địa chỉ 10', GETDATE()),
('Khách hàng 11', '0909000011', 'kh11@mail.com', 'Địa chỉ 11', GETDATE()),
('Khách hàng 12', '0909000012', 'kh12@mail.com', 'Địa chỉ 12', GETDATE()),
('Khách hàng 13', '0909000013', 'kh13@mail.com', 'Địa chỉ 13', GETDATE()),
('Khách hàng 14', '0909000014', 'kh14@mail.com', 'Địa chỉ 14', GETDATE()),
('Khách hàng 15', '0909000015', 'kh15@mail.com', 'Địa chỉ 15', GETDATE()),
('Khách hàng 16', '0909000016', 'kh16@mail.com', 'Địa chỉ 16', GETDATE()),
('Khách hàng 17', '0909000017', 'kh17@mail.com', 'Địa chỉ 17', GETDATE()),
('Khách hàng 18', '0909000018', 'kh18@mail.com', 'Địa chỉ 18', GETDATE()),
('Khách hàng 19', '0909000019', 'kh19@mail.com', 'Địa chỉ 19', GETDATE()),
('Khách hàng 20', '0909000020', 'kh20@mail.com', 'Địa chỉ 20', GETDATE());

-- SQL Server FIX:
-- slug is NULL for all seed categories. A normal UNIQUE constraint on a nullable
-- column would allow only one NULL in SQL Server, so categories would fail here.
-- The filtered unique index above allows multiple NULLs and still enforces
-- uniqueness whenever slug has a value.
-- ===== CATEGORIES (name) =====
INSERT INTO categories (name, created_at)
VALUES
('Đồ uống', GETDATE()),
('Bánh kẹo', GETDATE()),
('Gia vị', GETDATE()),
('Đồ gia dụng', GETDATE()),
('Mỹ phẩm', GETDATE()),
('Thực phẩm tươi sống', GETDATE()),         
('Điện tử & Phụ kiện', GETDATE()),       
('Dược phẩm & Y tế', GETDATE()),     
('Văn phòng phẩm', GETDATE()),      
('Thủy hải sản', GETDATE());

-- ===== SUPPLIERS (name, contact_name, phone, email, address) =====
INSERT INTO suppliers (name, contact_name, phone, email, address, created_at)
VALUES
('Công ty TNHH Đồ uống Quốc tế ABC', 'Nguyễn Văn A', '0909123456', 'abc@gmail.com', 'Số 123, Đường Láng, Quận Đống Đa, Hà Nội', GETDATE()),
('Công ty CP Thương mại & Phân phối XYZ', 'Trần Thị B', '0912123456', 'xyz@gmail.com', 'Số 456, Nguyễn Văn Linh, Quận 7, TP HCM', GETDATE()),
('Công ty TNHH Sản xuất 123', 'Lê Văn C', '0933123456', '123@gmail.com', 'Số 789, Đường 2/9, Quận Hải Châu, Đà Nẵng', GETDATE()),
('Công ty Thực phẩm Việt', 'Phạm Minh D', '0909123457', 'thucphamviet@company.com', 'Khu công nghiệp Bắc Thăng Long, Hà Nội', GETDATE()),
('Công ty Đồ uống Sài Gòn', 'Hoàng Thị E', '0912123457', 'douongsaigon@company.com', 'Số 321, Lê Văn Việt, Quận 9, TP HCM', GETDATE()),
('Công ty Gia dụng Toàn Cầu', 'Đặng Văn F', '0933123457', 'giadungtoancau@company.com', 'Khu công nghiệp Hòa Khánh, Đà Nẵng', GETDATE()),
('Công ty Mỹ phẩm Hàn Quốc', 'Kim Soo G', '0909123458', 'myphamkorea@company.com', 'Tầng 5, Tòa nhà Vina, Quận 1, TP HCM', GETDATE()),
('Công ty Bánh kẹo Hữu Nghị', 'Ngô Thị H', '0912123458', 'banhkeohuunghi@company.com', 'Số 55, Minh Khai, Quận Hai Bà Trưng, Hà Nội', GETDATE()),
('Công ty Gia vị Phương Nam', 'Võ Văn I', '0933123458', 'giaviphuongnam@company.com', 'Khu chế xuất Tân Thuận, Quận 7, TP HCM', GETDATE()),
('Công ty Điện tử Viễn Thông', 'Trương Văn J', '0909123459', 'dientuvienthong@company.com', 'Khu công nghiệp Sóng Thần, Bình Dương', GETDATE()),
('Công ty Văn phòng phẩm STC', 'Lý Thị K', '0912123459', 'vanphongphamstc@company.com', 'Số 88, Lê Hồng Phong, Quận 10, TP HCM', GETDATE()),
('Công ty Dược phẩm Việt Đức', 'Mai Văn L', '0933123459', 'duocphamvietduc@company.com', 'Khu công nghiệp Yên Phong, Bắc Ninh', GETDATE()),
('Công ty Thủy hải sản Biển Đông', 'Bùi Thị M', '0909123460', 'haisanbiendong@company.com', 'Cảng cá Thọ Quang, Đà Nẵng', GETDATE());

-- ===== THÊM DỮ LIỆU MẪU CHO BẢNG UNITS =====
INSERT INTO units (code, name, created_at) VALUES
('pcs', 'Cái', GETDATE()),
('box', 'Hộp', GETDATE()),
('bottle', 'Chai', GETDATE()),
('can', 'Lon', GETDATE()),
('tube', 'Tuýp', GETDATE()),
('pack', 'Gói', GETDATE()),
('kg', 'Kilogram', GETDATE()),
('liter', 'Lít', GETDATE()),
('pair', 'Đôi', GETDATE()),
('set', 'Bộ', GETDATE()),
('roll', 'Cuộn', GETDATE()),             
('sheet', 'Tờ', GETDATE()),             
('bag', 'Túi', GETDATE());             

-- ===== PRODUCTS (category_id, supplier_id, product_name, sku, price, unit) =====
INSERT INTO products (category_id, supplier_id, product_name, sku, price, unit_id, created_at)
VALUES
(1, 1, 'Coca Cola lon', '8900000000001', 15000.00, 4, GETDATE()),
(1, 5, 'Pepsi lon', '8900000000002', 15000.00, 4, GETDATE()),
(1, 1, 'Trà Xanh 0 độ', '8900000000003', 12000.00, 3, GETDATE()),
(1, 5, 'Sting dâu', '8900000000004', 12000.00, 3, GETDATE()),
(1, 1, 'Red Bull', '8900000000005', 20000.00, 4, GETDATE()),
(1, 1, 'Nước ngọt Sprite', '8900000000046', 15000.00, 3, GETDATE()),
(1, 5, 'Trà sữa đóng chai', '8900000000047', 20000.00, 3, GETDATE()),
(1, 5, 'Nước cam ép', '8900000000054', 25000.00, 3, GETDATE()),
(1, 5, 'Sinh tố đóng chai', '8900000000055', 30000.00, 3, GETDATE()),
(1, 5, 'Bia Tiger lon', '8900000000056', 20000.00, 4, GETDATE()),
(1, 1, 'Trà Lipton', '8900000000027', 10000.00, 3, GETDATE()),
(1, 4, 'Sữa Vinamilk', '8900000000028', 12000.00, 3, GETDATE()),
(1, 4, 'Sữa TH 1 Milk', '8900000000029', 15000.00, 3, GETDATE()),
(1, 5, 'Nước suối Lavie', '8900000000030', 8000.00, 4, GETDATE()),
(1, 9, 'Cà phê G7', '8900000000026', 50000.00, 3, GETDATE()),
(2, 8, 'Bánh Oreo', '8900000000006', 25000.00, 6, GETDATE()),
(2, 8, 'Bánh Chocopie', '8900000000007', 20000.00, 6, GETDATE()),
(2, 8, 'Kẹo Alpenliebe', '8900000000008', 5000.00, 6, GETDATE()),
(2, 8, 'Kẹo bạc hà', '8900000000009', 10000.00, 6, GETDATE()),
(2, 8, 'Socola KitKat', '8900000000010', 15000.00, 6, GETDATE()),
(2, 4, 'Snack Oishi', '8900000000048', 10000.00, 6, GETDATE()),
(2, 8, 'Snack Lay''s', '8900000000049', 15000.00, 6, GETDATE()),
(2, 8, 'Kẹo dẻo Haribo', '8900000000050', 20000.00, 6, GETDATE()),
(2, 8, 'Bánh quy bơ', '8900000000063', 30000.00, 6, GETDATE()),
(2, 8, 'Kẹo cao su', '8900000000064', 5000.00, 6, GETDATE()),
(2, 8, 'Bánh gato mini', '8900000000065', 50000.00, 2, GETDATE()),
(3, 9, 'Nước mắm Nam Ngư', '8900000000011', 35000.00, 3, GETDATE()),
(3, 9, 'Nước tương Maggi', '8900000000012', 25000.00, 3, GETDATE()),
(3, 9, 'Muối i-ốt', '8900000000013', 5000.00, 6, GETDATE()),
(3, 9, 'Bột ngọt Ajinomoto', '8900000000014', 15000.00, 6, GETDATE()),
(3, 9, 'Dầu ăn Tường An', '8900000000015', 45000.00, 3, GETDATE()),
(3, 9, 'Hạt nêm Knorr', '8900000000066', 20000.00, 6, GETDATE()),
(3, 9, 'Tương ớt Chin-su', '8900000000067', 15000.00, 3, GETDATE()),
(3, 9, 'Giấm gạo lên men', '8900000000068', 12000.00, 3, GETDATE()),
(4, 6, 'Nồi cơm điện', '8900000000016', 500000.00, 1, GETDATE()),
(4, 6, 'Ấm siêu tốc', '8900000000017', 300000.00, 1, GETDATE()),
(4, 6, 'Quạt máy', '8900000000018', 400000.00, 1, GETDATE()),
(4, 6, 'Bếp gas mini', '8900000000019', 600000.00, 1, GETDATE()),
(4, 6, 'Máy xay sinh tố', '8900000000020', 350000.00, 1, GETDATE()),
(4, 6, 'Bình nước Lock&Lock', '8900000000033', 150000.00, 1, GETDATE()),
(4, 6, 'Hộp nhựa Tupperware', '8900000000034', 80000.00, 1, GETDATE()),
(4, 6, 'Dao Inox', '8900000000035', 50000.00, 1, GETDATE()),
(4, 6, 'Nồi áp suất điện', '8900000000057', 800000.00, 1, GETDATE()),
(4, 6, 'Lò vi sóng', '8900000000058', 1200000.00, 1, GETDATE()),
(4, 6, 'Máy lọc không khí', '8900000000059', 1500000.00, 1, GETDATE()),
(5, 7, 'Sữa rửa mặt Hazeline', '8900000000021', 75000.00, 5, GETDATE()),
(5, 7, 'Kem dưỡng da Pond''s', '8900000000022', 120000.00, 5, GETDATE()),
(5, 7, 'Dầu gội Sunsilk', '8900000000023', 80000.00, 3, GETDATE()),
(5, 7, 'Sữa tắm Dove', '8900000000024', 90000.00, 3, GETDATE()),
(5, 7, 'Nước hoa Romano', '8900000000025', 250000.00, 3, GETDATE()),
(5, 7, 'Serum chống lão hóa', '8900000000060', 350000.00, 3, GETDATE()),
(5, 7, 'Mặt nạ dưỡng da', '8900000000061', 20000.00, 1, GETDATE()),
(5, 7, 'Kem chống nắng SPF50', '8900000000062', 150000.00, 5, GETDATE()),
(6, 4, 'Bánh mì sandwich', '8900000000041', 20000.00, 1, GETDATE()),
(6, 4, 'Thịt bò tươi', '8900000000051', 250000.00, 7, GETDATE()),
(6, 4, 'Cá hồi phi lê', '8900000000052', 350000.00, 7, GETDATE()),
(6, 4, 'Rau củ đông lạnh', '8900000000053', 50000.00, 6, GETDATE()),
(6, 4, 'Mì gói Hảo Hảo', '8900000000042', 5000.00, 6, GETDATE()),
(6, 4, 'Mì Omachi', '8900000000043', 7000.00, 6, GETDATE()),
(6, 4, 'Bún khô', '8900000000044', 15000.00, 6, GETDATE()),
(6, 4, 'Phở ăn liền', '8900000000045', 10000.00, 6, GETDATE()),
(7, 10, 'Tai nghe Bluetooth', '8900000000069', 300000.00, 1, GETDATE()),
(7, 10, 'Sạc dự phòng', '8900000000070', 200000.00, 1, GETDATE()),
(7, 10, 'Cáp sạc nhanh', '8900000000071', 50000.00, 1, GETDATE()),
(8, 12, 'Bàn chải Colgate', '8900000000036', 25000.00, 1, GETDATE()),
(8, 12, 'Kem đánh răng P/S', '8900000000037', 35000.00, 5, GETDATE()),
(8, 12, 'Nước súc miệng Listerine', '8900000000038', 45000.00, 3, GETDATE()),
(8, 12, 'Bông tẩy trang', '8900000000039', 20000.00, 6, GETDATE()),
(8, 12, 'Khẩu trang 3M', '8900000000040', 50000.00, 6, GETDATE()),
(8, 12, 'Vitamin C 500mg', '8900000000075', 80000.00, 6, GETDATE()),
(8, 12, 'Paracetamol 500mg', '8900000000076', 15000.00, 6, GETDATE()),
(8, 12, 'Băng gạc y tế', '8900000000077', 25000.00, 6, GETDATE()),
(9, 11, 'Khăn giấy Tempo', '8900000000031', 20000.00, 6, GETDATE()),
(9, 11, 'Giấy vệ sinh Pulppy', '8900000000032', 35000.00, 10, GETDATE()),
(9, 11, 'Bút bi xanh', '8900000000072', 5000.00, 1, GETDATE()),
(9, 11, 'Vở học sinh 96 trang', '8900000000073', 15000.00, 1, GETDATE()),
(9, 11, 'Bút highlight', '8900000000074', 12000.00, 1, GETDATE()),
(10, 13, 'Tôm sú tươi', '8900000000078', 280000.00, 7, GETDATE()),
(10, 13, 'Mực ống', '8900000000079', 220000.00, 7, GETDATE()),
(10, 13, 'Cá ngừ đại dương', '8900000000080', 320000.00, 7, GETDATE());

-- ===== INVENTORY (product_id, quantity) =====
INSERT INTO inventory (product_id, quantity, updated_at)
VALUES
(1, 25, GETDATE()),(2, 169, GETDATE()),(3, 77, GETDATE()),(4, 169, GETDATE()),(5, 90, GETDATE()),
(6, 105, GETDATE()),(7, 125, GETDATE()),(8, 37, GETDATE()),(9, 74, GETDATE()),(10, 149, GETDATE()),
(11, 69, GETDATE()),(12, 23, GETDATE()),(13, 46, GETDATE()),(14, 144, GETDATE()),(15, 134, GETDATE()),
(16, 182, GETDATE()),(17, 99, GETDATE()),(18, 72, GETDATE()),(19, 128, GETDATE()),(20, 123, GETDATE()),
(21, 155, GETDATE()),(22, 78, GETDATE()),(23, 166, GETDATE()),(24, 117, GETDATE()),(25, 168, GETDATE()),
(26, 197, GETDATE()),(27, 36, GETDATE()),(28, 145, GETDATE()),(29, 61, GETDATE()),(30, 139, GETDATE()),
(31, 47, GETDATE()),(32, 154, GETDATE()),(33, 194, GETDATE()),(34, 41, GETDATE()),(35, 154, GETDATE()),
(36, 71, GETDATE()),(37, 49, GETDATE()),(38, 165, GETDATE()),(39, 73, GETDATE()),(40, 176, GETDATE()),
(41, 41, GETDATE()),(42, 34, GETDATE()),(43, 175, GETDATE()),(44, 59, GETDATE()),(45, 198, GETDATE()),
(46, 106, GETDATE()),(47, 99, GETDATE()),(48, 55, GETDATE()),(49, 62, GETDATE()),(50, 33, GETDATE()),
(51, 45, GETDATE()),(52, 67, GETDATE()),(53, 88, GETDATE()),(54, 92, GETDATE()),(55, 76, GETDATE()),
(56, 54, GETDATE()),(57, 63, GETDATE()),(58, 71, GETDATE()),(59, 82, GETDATE()),(60, 93, GETDATE()),
(61, 105, GETDATE()),(62, 114, GETDATE()),(63, 126, GETDATE()),(64, 138, GETDATE()),(65, 147, GETDATE()),
(66, 155, GETDATE()),(67, 163, GETDATE()),(68, 172, GETDATE()),(69, 181, GETDATE()),(70, 192, GETDATE()),
(71, 203, GETDATE()),(72, 215, GETDATE()),(73, 224, GETDATE()),(74, 233, GETDATE()),(75, 242, GETDATE()),
(76, 251, GETDATE()),(77, 263, GETDATE()),(78, 274, GETDATE()),(79, 285, GETDATE()),(80, 296, GETDATE());

-- ===== PURCHASE ORDERS =====
INSERT INTO purchase_orders
(po_code, supplier_id, user_id, total_amount, note, status, created_at)
VALUES
('PO0001', 1, 2, 12500000, N'Nhập bổ sung nhóm đồ uống', 'completed', GETDATE()),
('PO0002', 8, 3, 8500000, N'Nhập bánh kẹo định kỳ', 'completed', GETDATE()),
('PO0003', 4, 2, 6200000, N'Nhập thực phẩm tươi sống', 'pending', GETDATE());

INSERT INTO po_details
(purchase_order_id, product_id, quantity, import_price)
VALUES
(1, 1, 200, 10000),
(1, 2, 200, 10000),
(1, 3, 150, 8000),
(2, 16, 100, 16000),
(2, 17, 100, 13000),
(2, 18, 200, 3000),
(3, 42, 100, 3500),
(3, 43, 100, 5000),
(3, 44, 50, 35000);

-- ===== INVENTORY ADJUSTMENTS =====
INSERT INTO inventory_adjustments
(product_id, change_amount, reason, user_id, created_at)
VALUES
(1, 200, 'Nhập hàng PO0001', 2, GETDATE()),
(2, 200, 'Nhập hàng PO0001', 2, GETDATE()),
(16, 100, 'Nhập hàng PO0002', 3, GETDATE()),
(42, 100, 'Nhập hàng PO0003', 2, GETDATE()),
(1, -2, 'Hàng hư hỏng', 3, GETDATE());

-- ===== PROMOTIONS =====
INSERT INTO promotions
(code, name, type, description, start_date, end_date, status, max_discount, usage_limit, used_count, created_at)
VALUES
('SALE10', N'Giảm 10%', 'event', N'Giảm 10% cho đơn hàng đủ điều kiện', '2025-01-01', '2025-12-31', 'expired', 50000, NULL, 0, GETDATE()),
('FREESHIP50K', N'Giảm 50K', 'event', N'Giảm 50.000 cho đơn từ 300.000', '2025-03-01', '2025-12-31', 'expired', 50000, 500, 0, GETDATE()),
('NEWUSER', N'Khách hàng mới', 'voucher', N'Giảm 20% cho khách hàng mới', '2025-01-01', '2025-06-30', 'expired', 100000, 1, 0, GETDATE()),
('SUMMER15', N'Khuyến mãi mùa hè', 'event', N'Giảm 15% mùa hè', '2025-06-01', '2025-08-31', 'expired', 100000, 1000, 0, GETDATE()),
('VIP100K', N'Khách VIP', 'voucher', N'Giảm 100.000 cho khách VIP', '2025-01-01', '2025-12-31', 'expired', 100000, 200, 0, GETDATE()),
('PROD15', N'Giảm 15% Coca/Pepsi', 'product', N'Giảm 15% cho một số sản phẩm đồ uống', '2025-01-01', '2025-12-31', 'expired', 100000, 500, 0, GETDATE());

-- Chi tiết event promotion
INSERT INTO event_promotions (promotion_id, min_order_amount, discount_percent, max_discount_amount)
VALUES
(1, 0, 10, 50000),
(2, 300000, 0, 50000),
(4, 50000, 15, 100000);

-- Chi tiết voucher promotion
INSERT INTO voucher_promotions
(promotion_id, voucher_code, discount_percent, max_discount_amount, usage_limit, used_count)
VALUES
(3, 'NEWUSER20', 20, 100000, 1, 0),
(5, 'VIP100K', 0, 100000, 200, 0);

-- Khuyến mãi áp dụng trực tiếp cho sản phẩm
INSERT INTO product_promotions (promotion_id, product_id, discount_percent)
VALUES
(6, 1, 15),
(6, 2, 15);

-- ===== ORDERS với giá mới hợp lý =====
INSERT INTO orders (order_number, customer_id, employee_id, order_type, status, subtotal, discount, total_amount, promotion_id, payment_method, payment_status, created_at)
VALUES
(CONVERT(varchar(36), NEWID()), 5, 3, 'pos', 'completed', 285000, 28500, 256500, 1, 'cash', 'paid', GETDATE()), -- Order 1: 10% discount
(CONVERT(varchar(36), NEWID()), 17, 3, 'pos', 'completed', 420000, 0, 420000, NULL, 'e_wallet', 'paid', GETDATE()), -- Order 2: No discount
(CONVERT(varchar(36), NEWID()), 8, 3, 'pos', 'completed', 185000, 0, 185000, NULL, 'e_wallet', 'paid', GETDATE()), -- Order 3: No discount
(CONVERT(varchar(36), NEWID()), 20, 3, 'pos', 'completed', 40000, 4000, 36000, 1, 'card', 'paid', GETDATE()), -- Order 4: 10% discount
(CONVERT(varchar(36), NEWID()), 1, 2, 'pos', 'completed', 75000, 0, 75000, NULL, 'cash', 'paid', GETDATE()), -- Order 5
(CONVERT(varchar(36), NEWID()), 5, 3, 'pos', 'completed', 620000, 50000, 570000, 2, 'cash', 'paid', GETDATE()), -- Order 6: Fixed 50k
(CONVERT(varchar(36), NEWID()), 9, 3, 'pos', 'completed', 350000, 52500, 297500, 4, 'e_wallet', 'paid', GETDATE()), -- Order 7: 15% discount
(CONVERT(varchar(36), NEWID()), 11, 3, 'pos', 'completed', 280000, 56000, 224000, 3, 'cash', 'paid', GETDATE()), -- Order 8: 20% discount
(CONVERT(varchar(36), NEWID()), 11, 3, 'pos', 'completed', 450000, 0, 450000, NULL, 'cash', 'paid', GETDATE()), -- Order 9
(CONVERT(varchar(36), NEWID()), 11, 3, 'pos', 'completed', 320000, 50000, 270000, 2, 'card', 'paid', GETDATE()), -- Order 10: Fixed 50k
(CONVERT(varchar(36), NEWID()), 20, 3, 'pos', 'completed', 380000, 0, 380000, NULL, 'e_wallet', 'paid', GETDATE()), -- Order 11
(CONVERT(varchar(36), NEWID()), 10, 2, 'pos', 'completed', 275000, 0, 275000, NULL, 'card', 'paid', GETDATE()), -- Order 12
(CONVERT(varchar(36), NEWID()), 10, 3, 'pos', 'completed', 410000, 50000, 360000, 2, 'card', 'paid', GETDATE()), -- Order 13: Fixed 50k
(CONVERT(varchar(36), NEWID()), 6, 2, 'pos', 'completed', 520000, 50000, 470000, 2, 'cash', 'paid', GETDATE()), -- Order 14: Fixed 50k
(CONVERT(varchar(36), NEWID()), 10, 2, 'pos', 'completed', 90000, 18000, 72000, 3, 'card', 'paid', GETDATE()), -- Order 15: 20% discount
(CONVERT(varchar(36), NEWID()), 10, 2, 'pos', 'completed', 280000, 50000, 230000, 2, 'cash', 'paid', GETDATE()), -- Order 16: Fixed 50k
(CONVERT(varchar(36), NEWID()), 19, 3, 'pos', 'completed', 150000, 0, 150000, NULL, 'cash', 'paid', GETDATE()), -- Order 17
(CONVERT(varchar(36), NEWID()), 10, 2, 'pos', 'completed', 120000, 0, 120000, NULL, 'e_wallet', 'paid', GETDATE()), -- Order 18
(CONVERT(varchar(36), NEWID()), 8, 3, 'pos', 'completed', 680000, 102000, 578000, 4, 'card', 'paid', GETDATE()), -- Order 19: 15% discount
(CONVERT(varchar(36), NEWID()), 3, 3, 'pos', 'completed', 850000, 0, 850000, NULL, 'card', 'paid', GETDATE()), -- Order 20
(CONVERT(varchar(36), NEWID()), 9, 2, 'pos', 'completed', 720000, 0, 720000, NULL, 'cash', 'paid', GETDATE()), -- Order 21
(CONVERT(varchar(36), NEWID()), 17, 3, 'pos', 'completed', 95000, 0, 95000, NULL, 'e_wallet', 'paid', GETDATE()), -- Order 22
(CONVERT(varchar(36), NEWID()), 6, 3, 'pos', 'completed', 630000, 94500, 535500, 4, 'cash', 'paid', GETDATE()), -- Order 23: 15% discount
(CONVERT(varchar(36), NEWID()), 1, 3, 'pos', 'completed', 480000, 72000, 408000, 4, 'e_wallet', 'paid', GETDATE()), -- Order 24: 15% discount
(CONVERT(varchar(36), NEWID()), 2, 2, 'pos', 'completed', 220000, 44000, 176000, 3, 'cash', 'paid', GETDATE()), -- Order 25: 20% discount
(CONVERT(varchar(36), NEWID()), 15, 3, 'pos', 'completed', 180000, 36000, 144000, 3, 'cash', 'paid', GETDATE()), -- Order 26: 20% discount
(CONVERT(varchar(36), NEWID()), 4, 2, 'pos', 'completed', 310000, 0, 310000, NULL, 'cash', 'paid', GETDATE()), -- Order 27
(CONVERT(varchar(36), NEWID()), 16, 2, 'pos', 'completed', 750000, 0, 750000, NULL, 'card', 'paid', GETDATE()), -- Order 28
(CONVERT(varchar(36), NEWID()), 4, 3, 'pos', 'completed', 920000, 138000, 782000, 4, 'cash', 'paid', GETDATE()), -- Order 29: 15% discount
(CONVERT(varchar(36), NEWID()), 1, 3, 'pos', 'completed', 1050000, 0, 1050000, NULL, 'card', 'paid', GETDATE()); -- Order 30

-- ===== ORDER_ITEMS với giá mới =====
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total_price, created_at)
VALUES
-- Order 1 (3 sản phẩm)
(1, 23, 2, 15000.00, 30000.00, GETDATE()), -- Snack Lay's
(1, 5, 1, 20000.00, 20000.00, GETDATE()),  -- Red Bull
(1, 47, 3, 20000.00, 60000.00, GETDATE()), -- Trà sữa đóng chai

-- Order 2 (2 sản phẩm)
(2, 39, 1, 20000.00, 20000.00, GETDATE()), -- Bông tẩy trang
(2, 14, 2, 12000.00, 24000.00, GETDATE()), -- Sữa Vinamilk

-- Order 3 (3 sản phẩm)
(3, 18, 1, 10000.00, 10000.00, GETDATE()), -- Kẹo bạc hà
(3, 34, 2, 80000.00, 160000.00, GETDATE()), -- Hộp nhựa Tupperware
(3, 26, 1, 15000.00, 15000.00, GETDATE()), -- Bánh quy bơ

-- Order 4 (2 sản phẩm)
(4, 24, 2, 20000.00, 40000.00, GETDATE()), -- Kẹo dẻo Haribo

-- Order 5 (1 sản phẩm)
(5, 9, 1, 75000.00, 75000.00, GETDATE()), -- Sữa rửa mặt Hazeline

-- Order 6 (5 sản phẩm)
(6, 18, 2, 10000.00, 20000.00, GETDATE()),
(6, 22, 1, 120000.00, 120000.00, GETDATE()),
(6, 42, 3, 5000.00, 15000.00, GETDATE()),
(6, 17, 2, 300000.00, 600000.00, GETDATE()),
(6, 20, 1, 400000.00, 400000.00, GETDATE()),

-- Order 7 (2 sản phẩm)
(7, 8, 2, 5000.00, 10000.00, GETDATE()),
(7, 8, 1, 5000.00, 5000.00, GETDATE()),

-- Order 8 (3 sản phẩm)
(8, 42, 1, 5000.00, 5000.00, GETDATE()),
(8, 43, 2, 7000.00, 14000.00, GETDATE()),
(8, 31, 3, 20000.00, 60000.00, GETDATE()),

-- Order 9 (4 sản phẩm)
(9, 17, 2, 300000.00, 600000.00, GETDATE()),
(9, 12, 1, 25000.00, 25000.00, GETDATE()),
(9, 43, 2, 7000.00, 14000.00, GETDATE()),
(9, 19, 1, 600000.00, 600000.00, GETDATE()),

-- Order 10 (4 sản phẩm)
(10, 25, 1, 250000.00, 250000.00, GETDATE()),
(10, 1, 2, 15000.00, 30000.00, GETDATE()),
(10, 23, 2, 15000.00, 30000.00, GETDATE()),
(10, 49, 2, 5000.00, 10000.00, GETDATE()),

-- Thêm thông tin cho các order còn lại...
-- (Giảm bớt để file không quá dài, bạn có thể thêm theo mẫu trên)
(11, 3, 1, 12000.00, 12000.00, GETDATE()),
(11, 23, 2, 15000.00, 30000.00, GETDATE()),
(12, 40, 1, 50000.00, 50000.00, GETDATE()),
(13, 24, 1, 20000.00, 20000.00, GETDATE()),
(14, 24, 2, 20000.00, 40000.00, GETDATE()),
(15, 18, 1, 10000.00, 10000.00, GETDATE()),
(16, 15, 1, 45000.00, 45000.00, GETDATE()),
(17, 42, 1, 5000.00, 5000.00, GETDATE()),
(18, 30, 1, 8000.00, 8000.00, GETDATE()),
(19, 16, 1, 500000.00, 500000.00, GETDATE()),
(20, 49, 1, 5000.00, 5000.00, GETDATE()),
(21, 11, 2, 35000.00, 70000.00, GETDATE()),
(22, 40, 1, 50000.00, 50000.00, GETDATE()),
(23, 1, 2, 15000.00, 30000.00, GETDATE()),
(24, 3, 3, 12000.00, 36000.00, GETDATE()),
(25, 9, 1, 75000.00, 75000.00, GETDATE()),
(26, 47, 2, 20000.00, 40000.00, GETDATE()),
(27, 37, 1, 35000.00, 35000.00, GETDATE()),
(28, 20, 3, 400000.00, 1200000.00, GETDATE()),
(29, 28, 1, 25000.00, 25000.00, GETDATE()),
(30, 25, 1, 250000.00, 250000.00, GETDATE());

-- ===== PAYMENTS với số tiền mới =====
INSERT INTO payments (order_id, amount, method, transaction_ref, status, created_at)
VALUES
(1, 256500.00, 'cash', NULL, 'completed', GETDATE()),
(2, 420000.00, 'e_wallet', NULL, 'completed', GETDATE()),
(3, 185000.00, 'e_wallet', NULL, 'completed', GETDATE()),
(4, 36000.00, 'card', NULL, 'completed', GETDATE()),
(5, 75000.00, 'cash', NULL, 'completed', GETDATE()),
(6, 570000.00, 'cash', NULL, 'completed', GETDATE()),
(7, 297500.00, 'e_wallet', NULL, 'completed', GETDATE()),
(8, 224000.00, 'cash', NULL, 'completed', GETDATE()),
(9, 450000.00, 'cash', NULL, 'completed', GETDATE()),
(10, 270000.00, 'card', NULL, 'completed', GETDATE()),
(11, 380000.00, 'e_wallet', NULL, 'completed', GETDATE()),
(12, 275000.00, 'card', NULL, 'completed', GETDATE()),
(13, 360000.00, 'card', NULL, 'completed', GETDATE()),
(14, 470000.00, 'cash', NULL, 'completed', GETDATE()),
(15, 72000.00, 'card', NULL, 'completed', GETDATE()),
(16, 230000.00, 'cash', NULL, 'completed', GETDATE()),
(17, 150000.00, 'cash', NULL, 'completed', GETDATE()),
(18, 120000.00, 'e_wallet', NULL, 'completed', GETDATE()),
(19, 578000.00, 'card', NULL, 'completed', GETDATE()),
(20, 850000.00, 'card', NULL, 'completed', GETDATE()),
(21, 720000.00, 'cash', NULL, 'completed', GETDATE()),
(22, 95000.00, 'e_wallet', NULL, 'completed', GETDATE()),
(23, 535500.00, 'cash', NULL, 'completed', GETDATE()),
(24, 408000.00, 'e_wallet', NULL, 'completed', GETDATE()),
(25, 176000.00, 'cash', NULL, 'completed', GETDATE()),
(26, 144000.00, 'cash', NULL, 'completed', GETDATE()),
(27, 310000.00, 'cash', NULL, 'completed', GETDATE()),
(28, 750000.00, 'card', NULL, 'completed', GETDATE()),
(29, 782000.00, 'cash', NULL, 'completed', GETDATE()),
(30, 1050000.00, 'card', NULL, 'completed', GETDATE());



-- ===== AI CONVERSATIONS & MESSAGES =====
CREATE TABLE ai_conversations (
  id INT IDENTITY(1,1) PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_conversations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_ai_conversations_user ON ai_conversations (user_id);

CREATE TABLE ai_messages (
  id BIGINT IDENTITY(1,1) PRIMARY KEY,
  conversation_id INT NOT NULL,
  role VARCHAR(20) NOT NULL,
  content NVARCHAR(MAX) NOT NULL,
  function_called VARCHAR(100),
  function_data NVARCHAR(MAX),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_messages_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_ai_messages_conversation ON ai_messages (conversation_id);

-- ===== VERIFICATION =====
SELECT DB_NAME() AS current_database;
SELECT name FROM sys.tables ORDER BY name;
SELECT COUNT(*) AS users_count FROM users;
SELECT COUNT(*) AS products_count FROM products;
SELECT COUNT(*) AS orders_count FROM [orders];
SELECT COUNT(*) AS purchase_orders_count FROM purchase_orders;
SELECT COUNT(*) AS promotions_count FROM promotions;
SELECT COUNT(*) AS employees_count FROM users WHERE role = 'employee';
SELECT COUNT(*) AS admins_count FROM users WHERE role = 'admin';
GO